### ISSUE TITLE
Rev Modul: Home

### ISSUE THREAD

**Issue by infomugi** [infomugi/irecruitment#1]
1. Halaman home ngikutin kaya yang recruitment [dot] sisi [dot] id
2. Disamping logo ish ada tulisan “E-Recruitment”

**Comment by infomugi** [comment]
Revisi Home
![1](https://user-images.githubusercontent.com/9348754/29262070-0c499904-80fd-11e7-8ee5-3a4263cb8cbf.png)

**Comment by taufikramdanh** [comment]
Mantapp a mantap, kalo persyaratannya nanti bisa di ganti kan a ?

**Comment by infomugi** [comment]
iya pik buat persyaratan itu bisa di ganti nantinya

**Comment by taufikramdanh** [comment]
a udah di pull tapi masih kaya pertama, belum berubah

**Comment by taufikramdanh** [comment]
![untitled](https://user-images.githubusercontent.com/29963718/29262933-870dd2da-808b-11e7-9d06-e43329a899c8.png)

**Comment by infomugi** [comment]
itu error nama dbnya engga sama, sama database pik

**Comment by taufikramdanh** [comment]
jadi harus di gimanain a ?

**Comment by infomugi** [comment]
pull lagi pik

**Comment by taufikramdanh** [comment]
Sipp udahh a, tinggal tulisan "E-Recruitment" nya a hehehe

**Comment by infomugi** [comment]
![2017-08-14_161229](https://user-images.githubusercontent.com/9348754/29265508-83b8c1a0-810b-11e7-8115-8f7b14529f7e.png)

Siap pik ini ya, tinggal di pull
